run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
    - typecheck
    - gofmt
    - goimports
    - misspell
    - gocritic
    - gosec
    - prealloc
    - exportloopref
    - revive

linters-settings:
  govet:
    check-shadowing: true
  gocritic:
    enabled-tags:
      - performance
      - style
      - diagnostic
  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
      - name: unused-parameter
        severity: warning
        disabled: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
